# Generated by Django 6.0.1 on 2026-02-10 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebapp', '0003_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='lesson_images/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='lesson_videos/'),
        ),
    ]
